insert into public."Profiles" (id, username, destination, hobbies) values (1, 'prace0', 'Dubrovnik', Array['surfing, adventure racing']);
insert into public."Profiles" (id, username, destination, hobbies) values (2, 'bstickney1', 'Paris', Array['backpacking, scuba diving, cultural immersion']);
insert into public."Profiles" (id, username, destination, hobbies) values (3, 'wwillmott2', 'Berlin', null);
insert into public."Profiles" (id, username, destination, hobbies) values (4, 'hsomersett3', 'Venice', Array['rock climbing, skydiving']);
insert into public."Profiles" (id, username, destination, hobbies) values (5, 'mgorry4', 'London', Array['yoga retreats']);
insert into public."Profiles" (id, username, destination, hobbies) values (6, 'khumburton5', 'Paris', Array['safari tours, scuba diving']);
insert into public."Profiles" (id, username, destination, hobbies) values (7, 'dheitz6', 'Barcelona', null);
insert into public."Profiles" (id, username, destination, hobbies) values (8, 'speer7', 'Reykjavík', null);
insert into public."Profiles" (id, username, destination, hobbies) values (9, 'flidington8', 'Paris', null);
insert into public."Profiles" (id, username, destination, hobbies) values (10, 'gwhitwam9', 'London', Array['bird watching, scuba diving']);
insert into public."Profiles" (id, username, destination, hobbies) values (11, 'bhenstonea', 'Barcelona', null);
insert into public."Profiles" (id, username, destination, hobbies) values (12, 'hrangleb', 'Amsterdam', Array['cave exploring, paragliding']);
insert into public."Profiles" (id, username, destination, hobbies) values (13, 'rswitsurc', 'Reykjavík', null);
insert into public."Profiles" (id, username, destination, hobbies) values (14, 'egatwardd', 'London', Array['adventure racing']);
insert into public."Profiles" (id, username, destination, hobbies) values (15, 'nbrouarde', 'Paris', Array['hot air ballooning, zip-lining']);
insert into public."Profiles" (id, username, destination, hobbies) values (16, 'rknevettf', 'Reykjavík', Array['backpacking']);
insert into public."Profiles" (id, username, destination, hobbies) values (17, 'ckilgalleng', 'London', Array['scuba diving, yoga retreats']);
insert into public."Profiles" (id, username, destination, hobbies) values (18, 'gellimanh', 'Amsterdam', Array['yoga retreats, cultural immersion, surfing']);
insert into public."Profiles" (id, username, destination, hobbies) values (19, 'hdechellei', 'Reykjavík', null);
insert into public."Profiles" (id, username, destination, hobbies) values (20, 'wloughreyj', 'Dubrovnik', Array['hiking']);
insert into public."Profiles" (id, username, destination, hobbies) values (21, 'chirjakk', 'Barcelona', Array['safari tours, mountain biking, scuba diving, hiking']);
insert into public."Profiles" (id, username, destination, hobbies) values (22, 'tmeinerl', 'Amsterdam', Array['safari tours']);
insert into public."Profiles" (id, username, destination, hobbies) values (23, 'rdoughertym', 'Amsterdam', null);
insert into public."Profiles" (id, username, destination, hobbies) values (24, 'pgreedyern', 'Barcelona', Array['volunteering, safari tours, paragliding']);
insert into public."Profiles" (id, username, destination, hobbies) values (25, 'mdayntero', 'Paris', Array['cave exploring, scuba diving']);
insert into public."Profiles" (id, username, destination, hobbies) values (26, 'bvanarsdalenp', 'Barcelona', Array['photography, bird watching, skydiving']);
insert into public."Profiles" (id, username, destination, hobbies) values (27, 'efitzharrisq', 'Reykjavík', Array['adventure racing, photography, cultural immersion, food tasting']);
insert into public."Profiles" (id, username, destination, hobbies) values (28, 'fbockmanr', 'Reykjavík', Array['cave exploring, backpacking, food tasting, zip-lining']);
insert into public."Profiles" (id, username, destination, hobbies) values (29, 'vlavingtons', 'Reykjavík', Array['hot air ballooning, safari tours, cultural immersion']);
insert into public."Profiles" (id, username, destination, hobbies) values (30, 'psimmanst', 'Reykjavík', Array['backpacking']);
insert into public."Profiles" (id, username, destination, hobbies) values (31, 'hthringu', 'Venice', Array['volunteering, food tasting, cave exploring']);
insert into public."Profiles" (id, username, destination, hobbies) values (32, 'cricardev', 'London', Array['kayaking']);
insert into public."Profiles" (id, username, destination, hobbies) values (33, 'calleynew', 'Venice', Array['surfing']);
insert into public."Profiles" (id, username, destination, hobbies) values (34, 'fcushworthx', 'Barcelona', Array['safari tours, hiking']);
insert into public."Profiles" (id, username, destination, hobbies) values (35, 'ivarrowy', 'London', Array['zip-lining']);